on: [push]

name: Build

jobs:
# Linux {{{

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Build
        run: >
          cargo build --release --features cli &&
          strip -s target/release/braque &&
          mv target/release/braque target/release/braque_amd64

      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Release Braque for Linux
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/braque')
        with:
          files: |
            target/release/braque_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
# Windows {{{

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features cli

      - name: Release Braque for Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/braque')
        with:
          files: target/release/braque.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
# MacOS {{{

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Build
        run: >
          cargo build --release --features cli &&
          strip -SxD target/release/braque &&
          mv target/release/braque target/release/braque_darwin

      - name: Release Braque for MacOS
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/braque')
        with:
          files: |
            target/release/braque_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
